### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by oculus42** [haoliangyu/gtran#1]
I attempted to `gtran` and `gtran-kml` and receive the following error when requiring the library:

```
> gtran = require('gtran')
WARNING: No configurations found in configuration directory:/project/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
ReferenceError: regeneratorRuntime is not defined
node_modules/gtran-kml/dist/index.js:24:46
    at Object.<anonymous> (/project/node_modules/gtran-kml/dist/index.js:73:2)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

Some preliminary research indicates this may be an issue with using `babel-preset-env` without the `regenerator-runtime`?

I tried on Node 8.9.3 and 9.8.0 on MacOS 10.13.3.

**Comment by haoliangyu** [comment]
@oculus42 Thanks for reporting this issue. I used the `aysnc/await` in a component library `gtran-kml` but did not add proper babel polyfill. I have updated the babel setting and published a new version for it. Now, this issue should have been fixed!
